// Code generated by Slice Machine. DO NOT EDIT.

import Accordion from "./Accordion/index.svelte";
import Carousel from "./Carousel/index.svelte";
import CollectionList from "./CollectionList/index.svelte";
import Gallery from "./Gallery/index.svelte";
import GridBand from "./GridBand/index.svelte";
import Hero from "./Hero/index.svelte";
import LeadText from "./LeadText/index.svelte";
import LocationMap from "./LocationMap/index.svelte";
import MediaFull from "./MediaFull/index.svelte";
import MediaText from "./MediaText/index.svelte";
import RichText from "./RichText/index.svelte";
import SectionGrid from "./SectionGrid/index.svelte";
import SplitFeature from "./SplitFeature/index.svelte";
import TextColumns from "./TextColumns/index.svelte";
import TitleBand from "./TitleBand/index.svelte";

export const components = {
  accordion: Accordion,
  carousel: Carousel,
  collection_list: CollectionList,
  gallery: Gallery,
  grid_band: GridBand,
  hero: Hero,
  lead_text: LeadText,
  location_map: LocationMap,
  media_full: MediaFull,
  media_text: MediaText,
  rich_text: RichText,
  section_grid: SectionGrid,
  split_feature: SplitFeature,
  text_columns: TextColumns,
  title_band: TitleBand,
};
